from .config import LANGUAGE

STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "app_name": "FoxProfile",
        "app_subtitle": "Anti-detect profile manager",
        "filter_title": "Filter",
        "filter_all": "All",
        "filter_running": "Running",
        "filter_proxy": "With proxy",
        "filter_direct": "No proxy",
        "filter_chrome": "Chrome engine",
        "col_profile": "Profile",
        "col_device": "Device",
        "col_proxy": "Proxy",
        "col_geo": "Timezone · Locale",
        "col_status": "Status",
        "direct_short": "Direct",
        "follows_ip": "Follows IP",
        "stamp_live": "Running",
        "stamp_starting": "Starting",
        "stamp_idle": "Stopped",
        "stamp_failed": "Failed",
        "bulk_skip_running": "Skipped {count} running profile(s); stop them before deleting",
        "chrome_engine_unsupported": "The Chrome engine cannot run on this machine: {reason}",
        "engine_locked": "The engine cannot be changed after creation.",
        "proxy_format_hint": "user:pass@host:port, host:port:user:pass or socks5://... Blank = direct connection.",
        "geo_follow_hint": "Leave timezone and locale blank to follow the proxy's IP.",
        "no_fingerprint_short": "no fingerprint yet",
        "no_proxy_short": "no proxy",
        "profiles_none_running": "none running",
        "no_filter_results": "No profile in this filter",
        "clear_filters": "Clear filters",
        "mcp_button": "Connect AI (MCP)",
        "mcp_title": "Connect an AI agent (MCP)",
        "mcp_intro": "Let Claude, Cursor or VS Code manage profiles and browse for you: open pages, read them, click, type and take screenshots.",
        "mcp_endpoint": "MCP endpoint: {url}",
        "mcp_status_ok": "● FoxProfile API is running",
        "mcp_status_down": "● API not reachable: {error}",
        "mcp_pick_client": "1. Pick your AI app",
        "mcp_paste_into": "2. Paste into: {where}",
        "mcp_copy": "Copy",
        "mcp_copied": "Copied to clipboard",
        "mcp_show_token": "Include the real API token (otherwise a placeholder)",
        "mcp_restart": "3. Restart the AI app, keep FoxProfile running, then try:",
        "mcp_example_prompt": "Open profile shop-facebook-01, go to facebook.com and send me a screenshot.",
        "mcp_desktop_note": "Claude Desktop starts FoxProfile's MCP bridge with this computer's Python, so this config only works on this machine.",
        "mcp_security_note": "Page content is untrusted: the AI is told never to follow instructions found on web pages. Profiles cannot be deleted through MCP.",
        "window_title": "FoxProfile",
        "your_profiles": "Profiles",
        "search_hint": "Search by name or proxy",
        "no_search_results": 'No profile matches "{query}"',
        "no_profiles_yet": "No profiles yet",
        "create_profile_hint": "Create a new profile to get started",
        "new_profile": "New Profile",
        "import": "Import",
        "export": "Export",
        "total_profiles": "Total Profiles: {count}",
        "create_new_profile": "Create New Profile",
        "edit_profile": "Edit Profile",
        "editing_profile": "Editing: {name}",
        "configure_identity": "Configure your browser identity",
        "add_profile": "Add Profile",
        "profile_name": "Profile Name",
        "enter_profile_name": "Enter a profile name",
        "proxy_optional": "Proxy",
        "proxy_hint": "user:pass@ip:port",
        "profile_busy": "'{name}' is busy (starting or a cookie operation), try again shortly",
        "operating_system": "Operating System",
        "browser_engine": "Engine",
        "engine_camoufox": "Camoufox (Firefox)",
        "engine_chrome": "Chrome (experimental)",
        "engine_chrome_short": "Chrome",
        "engine_chrome_note": "Experimental Chromium engine. It is downloaded automatically the first time (~150 MB). Pick the OS of this machine: other OSes leak its fonts. The engine cannot be changed later.",
        "chrome_engine_downloading": "Downloading the Chrome engine in the background (~150 MB)...",
        "chrome_engine_ready": "Chrome engine is ready",
        "chrome_engine_download_failed": "Chrome engine download failed: {error}",
        "create_profile_btn": "Create Profile",
        "save_changes": "Save Changes",
        "cancel": "Cancel",
        "close_btn": "Close",
        "delete": "Delete",
        "check_proxy": "Check Proxy",
        "enter_proxy_to_check": "Enter a proxy to check",
        "launch": "Launch",
        "stop": "Stop",
        "loading": "Loading...",
        "previous": "Previous",
        "next": "Next",
        "page_of": "Page {current} of {total}",
        "activity_log": "Activity Log",
        "status_running": "RUNNING",
        "proxy_active": "PROXY ACTIVE",
        "direct_connection": "DIRECT CONNECTION",
        "tooltip_edit": "Edit profile",
        "tooltip_delete": "Delete profile",
        "tooltip_select": "Select profile",
        "tooltip_cookies": "Cookies & fingerprint",
        "confirm_delete_msg": "Delete profile '{name}'? Its cookies and data are removed permanently.",
        "confirm_bulk_delete": "Delete {count} profile(s)?",
        "cannot_undo": "This action cannot be undone.",
        "confirm_reset_fingerprint": "Create a new fingerprint for '{name}'? Sites will see a different machine.",
        "log_no_activity": "No activity yet.",
        "log_entries": "{count} entries",
        "profiles_configured": "Profiles: {count}",
        "profiles_running_suffix": "running",
        "browsers_running": "●  {count} browser(s) running",
        "no_active_sessions": "○  No active sessions",
        "selected_count": "{count} selected",
        "select_page": "Select Page",
        "deselect_page": "Deselect Page",
        "clear": "Clear",
        "error": "Error",
        "profile_exists": "Profile already exists!",
        "update_failed": "Could not update profile (Name might exist)",
        "stop_before_rename": "Stop the browser before renaming",
        "created_profile": "Created: {name}",
        "deleted_profile": "Deleted: {name}",
        "updated_profile": "Updated: {old} -> {new}",
        "launching_profile": "Launching {name}...",
        "stopping_profile": "Stopping {name}...",
        "starting_profile": "Starting {name} ({os})...",
        "browser_started": "Browser started!",
        "session_ended": "Session ended: {name}",
        "error_starting": "Error starting process: {error}",
        "export_profile": "Export Profile",
        "export_profiles": "Export Profiles",
        "choose_profiles_to_export": "Choose profiles to export",
        "select_all": "Select all",
        "include_browser_data": "Include browser data",
        "select_export_dir": "Select export directory",
        "import_profile": "Import Profile",
        "export_success": "Profile exported successfully",
        "import_success": "Profile imported successfully",
        "export_error": "Error exporting profile: {error}",
        "import_error": "Error importing profile: {error}",
        "validation_empty_name": "Profile name cannot be empty",
        "validation_name_too_long": "Profile name must be 64 characters or less",
        "validation_invalid_chars": "Name contains invalid characters: {chars}",
        "validation_name_spaces": "Name cannot start or end with spaces",
        "validation_trailing_dot": "Name cannot end with a dot",
        "validation_reserved_name": "'{name}' is a reserved system name",
        "validation_invalid_proxy": "Invalid proxy format. Use: [scheme://][user:pass@]host:port or host:port:user:pass",
        "validation_invalid_port": "Port must be between 1 and 65535, got {port}",
        "proxy_checking": "Checking proxy...",
        "proxy_check_success": "Proxy working. IP: {ip}",
        "proxy_check_failed": "Proxy check failed: {reason}",
        "proxy_check_skipped": "Proxy check skipped (aiohttp not installed)",
        "cookie_dialog_title": "Cookies & fingerprint",
        "cookie_dialog_hint": "Profile: {name}. The browser must be stopped.",
        "cookie_export_json": "Export JSON",
        "cookie_export_json_hint": "Cookie-Editor / EditThisCookie layout (GoLogin, GPM, Multilogin)",
        "cookie_export_netscape": "Export cookies.txt",
        "cookie_export_netscape_hint": "Netscape format (yt-dlp, curl, wget)",
        "cookie_import": "Import cookies",
        "cookie_import_hint": "From a JSON or cookies.txt file",
        "fingerprint_reset": "New fingerprint",
        "fingerprint_reset_hint": "Next launch presents a different device",
        "fingerprint_current": "Current device: {platform}, {screen}, {cores} cores",
        "fingerprint_none": "No fingerprint yet (created on first launch)",
        "cookie_stop_first": "Stop '{name}' before working with its cookies",
        "cookie_working": "[{name}] Reading cookies...",
        "cookie_exported": "[{name}] Exported {count} cookies to {path}",
        "cookie_imported": "[{name}] Imported {count} cookies",
        "cookie_error": "[{name}] Cookie error: {error}",
        "fingerprint_was_reset": "[{name}] Fingerprint reset; next launch uses a new device",
        "validation_invalid_timezone": "Unknown timezone '{value}' (use an IANA name such as Europe/Paris)",
        "validation_invalid_locale": "Invalid locale '{value}' (use language-REGION such as fr-FR)",
        "timezone_optional": "Timezone",
        "timezone_hint": "Follows IP · e.g. Asia/Ho_Chi_Minh",
        "locale_optional": "Locale",
        "locale_hint": "Follows IP · e.g. vi-VN",
        "check_ip": "Check IP",
        "ip_checking": "Checking IP...",
        "geo_exit": "Exit IP {ip} · {country}",
        "geo_timezone": "Timezone: {value} ({mode})",
        "geo_locale": "Language: {value} ({mode})",
        "geo_auto": "automatic",
        "geo_pinned": "pinned",
        "geo_locale_random": "random on every launch",
        "geo_source": "{source}: {ip} · {country} {city} · {timezone}",
        "geo_source_error": "{source}: failed ({error})",
        "geo_all_good": "No mismatch found",
        "geo_check_failed": "Could not get the exit IP: {error}",
        "geo_use_suggested": "Use {value}",
        "geo_warn_country_mismatch": "{source} places the IP in {got}; the browser uses {expected}",
        "geo_warn_timezone_mismatch": "{source} reports timezone {got}; the browser uses {expected}",
        "geo_warn_hosting": "{source} flags this IP as datacenter/hosting: expect captchas and blocks",
        "geo_warn_ip_differs": "Dual-stack proxy: the timezone follows {exit_ip} but sites see {seen_ip}",
        "geo_warn_locale_country": "Language {locale} does not belong to the IP's country ({country})",
        "geo_warn_locale_random": "Automatic language is re-drawn on every launch ({suggested} only ~{share}% of the time); pin it",
    },
    "vi": {
        "app_name": "FoxProfile",
        "app_subtitle": "Quản lý profile anti-detect",
        "filter_title": "Lọc",
        "filter_all": "Tất cả",
        "filter_running": "Đang chạy",
        "filter_proxy": "Có proxy",
        "filter_direct": "Không proxy",
        "filter_chrome": "Engine Chrome",
        "col_profile": "Profile",
        "col_device": "Thiết bị",
        "col_proxy": "Proxy",
        "col_geo": "Timezone · Locale",
        "col_status": "Trạng thái",
        "direct_short": "Trực tiếp",
        "follows_ip": "Theo IP",
        "stamp_live": "Đang chạy",
        "stamp_starting": "Đang mở",
        "stamp_idle": "Đã dừng",
        "stamp_failed": "Lỗi",
        "bulk_skip_running": "Bỏ qua {count} profile đang chạy; hãy dừng trước khi xoá",
        "chrome_engine_unsupported": "Máy này không chạy được engine Chrome: {reason}",
        "engine_locked": "Engine không đổi được sau khi tạo.",
        "proxy_format_hint": "user:pass@host:port, host:port:user:pass hoặc socks5://... Để trống = kết nối trực tiếp.",
        "geo_follow_hint": "Để trống timezone và locale thì tự theo IP của proxy.",
        "no_fingerprint_short": "chưa có fingerprint",
        "no_proxy_short": "không proxy",
        "profiles_none_running": "chưa có profile nào chạy",
        "no_filter_results": "Không có profile nào trong bộ lọc này",
        "clear_filters": "Xoá bộ lọc",
        "mcp_button": "Kết nối AI (MCP)",
        "mcp_title": "Kết nối AI agent (MCP)",
        "mcp_intro": "Cho Claude, Cursor hay VS Code tự quản lý profile và lướt web giúp bạn: mở trang, đọc nội dung, click, gõ và chụp màn hình.",
        "mcp_endpoint": "Địa chỉ MCP: {url}",
        "mcp_status_ok": "● API FoxProfile đang chạy",
        "mcp_status_down": "● Không kết nối được API: {error}",
        "mcp_pick_client": "1. Chọn ứng dụng AI bạn dùng",
        "mcp_paste_into": "2. Dán vào: {where}",
        "mcp_copy": "Sao chép",
        "mcp_copied": "Đã sao chép",
        "mcp_show_token": "Chèn token thật (nếu không sẽ là chỗ trống để tự điền)",
        "mcp_restart": "3. Khởi động lại ứng dụng AI, giữ FoxProfile đang chạy, rồi thử nhắn:",
        "mcp_example_prompt": "Mở profile shop-facebook-01, vào facebook.com và chụp màn hình cho tôi.",
        "mcp_desktop_note": "Claude Desktop chạy cầu nối MCP bằng Python của máy này, nên cấu hình này chỉ dùng được trên máy này.",
        "mcp_security_note": "Nội dung trang web không đáng tin: AI được dặn không làm theo chỉ dẫn nằm trên trang. MCP không thể xóa profile.",
        "window_title": "FoxProfile",
        "your_profiles": "Profile",
        "search_hint": "Tìm theo tên hoặc proxy",
        "no_search_results": 'Không có profile nào khớp "{query}"',
        "no_profiles_yet": "Chưa có profile nào",
        "create_profile_hint": "Tạo profile mới để bắt đầu",
        "new_profile": "Tạo profile",
        "import": "Nhập",
        "export": "Xuất",
        "total_profiles": "Tổng số profile: {count}",
        "create_new_profile": "Tạo profile mới",
        "edit_profile": "Sửa profile",
        "editing_profile": "Đang sửa: {name}",
        "configure_identity": "Thiết lập danh tính trình duyệt",
        "add_profile": "Thêm profile",
        "profile_name": "Tên profile",
        "enter_profile_name": "Nhập tên profile",
        "proxy_optional": "Proxy",
        "proxy_hint": "user:pass@ip:port",
        "profile_busy": "'{name}' đang bận (đang mở hoặc xử lý cookie), thử lại sau giây lát",
        "operating_system": "Hệ điều hành",
        "browser_engine": "Engine",
        "engine_camoufox": "Camoufox (Firefox)",
        "engine_chrome": "Chrome (thử nghiệm)",
        "engine_chrome_short": "Chrome",
        "engine_chrome_note": "Engine Chromium đang thử nghiệm. Lần đầu dùng sẽ tự tải về (~150 MB). Nên chọn đúng hệ điều hành của máy này, chọn hệ khác sẽ lộ font của máy. Không đổi được engine sau khi tạo.",
        "chrome_engine_downloading": "Đang tải engine Chrome ở nền (~150 MB)...",
        "chrome_engine_ready": "Engine Chrome đã sẵn sàng",
        "chrome_engine_download_failed": "Tải engine Chrome thất bại: {error}",
        "create_profile_btn": "Tạo profile",
        "save_changes": "Lưu thay đổi",
        "cancel": "Hủy",
        "close_btn": "Đóng",
        "delete": "Xóa",
        "check_proxy": "Kiểm tra proxy",
        "enter_proxy_to_check": "Nhập proxy để kiểm tra",
        "launch": "Mở",
        "stop": "Dừng",
        "loading": "Đang mở...",
        "previous": "Trước",
        "next": "Sau",
        "page_of": "Trang {current}/{total}",
        "activity_log": "Nhật ký hoạt động",
        "status_running": "ĐANG CHẠY",
        "proxy_active": "CÓ PROXY",
        "direct_connection": "KẾT NỐI TRỰC TIẾP",
        "tooltip_edit": "Sửa profile",
        "tooltip_delete": "Xóa profile",
        "tooltip_select": "Chọn profile",
        "tooltip_cookies": "Cookie & fingerprint",
        "confirm_delete_msg": "Xoá profile '{name}'? Cookie và dữ liệu của profile sẽ mất vĩnh viễn.",
        "confirm_bulk_delete": "Xóa {count} profile?",
        "cannot_undo": "Không thể hoàn tác thao tác này.",
        "confirm_reset_fingerprint": "Tạo fingerprint mới cho '{name}'? Trang web sẽ thấy đây là một máy khác.",
        "log_no_activity": "Chưa có hoạt động nào.",
        "log_entries": "{count} mục",
        "profiles_configured": "{count} profile",
        "profiles_running_suffix": "đang chạy",
        "browsers_running": "●  {count} trình duyệt đang chạy",
        "no_active_sessions": "○  Không có phiên nào",
        "selected_count": "Đã chọn {count}",
        "select_page": "Chọn cả trang",
        "deselect_page": "Bỏ chọn trang",
        "clear": "Bỏ chọn",
        "error": "Lỗi",
        "profile_exists": "Profile đã tồn tại!",
        "update_failed": "Không cập nhật được (có thể trùng tên)",
        "stop_before_rename": "Hãy dừng trình duyệt trước khi đổi tên",
        "created_profile": "Đã tạo: {name}",
        "deleted_profile": "Đã xóa: {name}",
        "updated_profile": "Đã cập nhật: {old} -> {new}",
        "launching_profile": "Đang mở {name}...",
        "stopping_profile": "Đang dừng {name}...",
        "starting_profile": "Khởi động {name} ({os})...",
        "browser_started": "Trình duyệt đã mở!",
        "session_ended": "Đã đóng: {name}",
        "error_starting": "Lỗi khi khởi động: {error}",
        "export_profile": "Xuất profile",
        "export_profiles": "Xuất profile",
        "choose_profiles_to_export": "Chọn profile cần xuất",
        "select_all": "Chọn tất cả",
        "include_browser_data": "Kèm dữ liệu trình duyệt",
        "select_export_dir": "Chọn thư mục lưu",
        "import_profile": "Nhập profile",
        "export_success": "Xuất profile thành công",
        "import_success": "Nhập profile thành công",
        "export_error": "Lỗi khi xuất profile: {error}",
        "import_error": "Lỗi khi nhập profile: {error}",
        "validation_empty_name": "Tên profile không được để trống",
        "validation_name_too_long": "Tên profile tối đa 64 ký tự",
        "validation_invalid_chars": "Tên chứa ký tự không hợp lệ: {chars}",
        "validation_name_spaces": "Tên không được bắt đầu hoặc kết thúc bằng dấu cách",
        "validation_trailing_dot": "Tên không được kết thúc bằng dấu chấm",
        "validation_reserved_name": "'{name}' là tên dành riêng của hệ thống",
        "validation_invalid_proxy": "Proxy sai định dạng. Dùng: [scheme://][user:pass@]host:port hoặc host:port:user:pass",
        "validation_invalid_port": "Port phải từ 1 đến 65535, nhận được {port}",
        "proxy_checking": "Đang kiểm tra proxy...",
        "proxy_check_success": "Proxy hoạt động. IP: {ip}",
        "proxy_check_failed": "Proxy lỗi: {reason}",
        "proxy_check_skipped": "Bỏ qua kiểm tra proxy (thiếu aiohttp)",
        "cookie_dialog_title": "Cookie & fingerprint",
        "cookie_dialog_hint": "Profile: {name}. Trình duyệt phải đang tắt.",
        "cookie_export_json": "Xuất JSON",
        "cookie_export_json_hint": "Định dạng Cookie-Editor / EditThisCookie (GoLogin, GPM, Multilogin)",
        "cookie_export_netscape": "Xuất cookies.txt",
        "cookie_export_netscape_hint": "Định dạng Netscape (yt-dlp, curl, wget)",
        "cookie_import": "Nhập cookie",
        "cookie_import_hint": "Từ file JSON hoặc cookies.txt",
        "fingerprint_reset": "Tạo fingerprint mới",
        "fingerprint_reset_hint": "Lần mở sau sẽ là một thiết bị khác",
        "fingerprint_current": "Fingerprint hiện tại: {platform}, {screen}, {cores} CPU",
        "fingerprint_none": "Chưa có fingerprint (sẽ tạo ở lần mở đầu)",
        "cookie_stop_first": "Hãy dừng '{name}' trước khi thao tác cookie",
        "cookie_working": "[{name}] Đang đọc cookie...",
        "cookie_exported": "[{name}] Đã xuất {count} cookie ra {path}",
        "cookie_imported": "[{name}] Đã nhập {count} cookie",
        "cookie_error": "[{name}] Lỗi cookie: {error}",
        "fingerprint_was_reset": "[{name}] Đã tạo fingerprint mới, lần mở sau dùng thiết bị mới",
        "validation_invalid_timezone": "Không có múi giờ '{value}' (dùng tên IANA, vd. Europe/Paris)",
        "validation_invalid_locale": "Locale '{value}' không hợp lệ (dạng ngôn_ngữ-QUỐC_GIA, vd. fr-FR)",
        "timezone_optional": "Timezone",
        "timezone_hint": "Theo IP · vd. Asia/Ho_Chi_Minh",
        "locale_optional": "Locale",
        "locale_hint": "Theo IP · vd. vi-VN",
        "check_ip": "Kiểm tra IP",
        "ip_checking": "Đang kiểm tra IP...",
        "geo_exit": "IP ra {ip} · {country}",
        "geo_timezone": "Timezone: {value} ({mode})",
        "geo_locale": "Locale: {value} ({mode})",
        "geo_auto": "tự động",
        "geo_pinned": "đặt tay",
        "geo_locale_random": "ngẫu nhiên mỗi lần mở",
        "geo_source": "{source}: {ip} · {country} {city} · {timezone}",
        "geo_source_error": "{source}: lỗi ({error})",
        "geo_all_good": "Không phát hiện điểm lệch",
        "geo_check_failed": "Không lấy được IP ra: {error}",
        "geo_use_suggested": "Dùng {value}",
        "geo_warn_country_mismatch": "{source} xác định IP ở {got}, trình duyệt đang dùng {expected}",
        "geo_warn_timezone_mismatch": "{source} báo múi giờ {got}, trình duyệt đang dùng {expected}",
        "geo_warn_hosting": "{source} gắn IP này là datacenter/hosting: dễ bị bắt captcha hoặc chặn",
        "geo_warn_ip_differs": "Proxy dual-stack: múi giờ tính theo {exit_ip} nhưng trang web thấy {seen_ip}",
        "geo_warn_locale_country": "Locale {locale} không thuộc quốc gia của IP ({country})",
        "geo_warn_locale_random": "Locale tự động được chọn lại ngẫu nhiên mỗi lần mở ({suggested} chỉ ~{share}% số lần); nên đặt cố định",
    },
}

_ACTIVE = STRINGS.get(LANGUAGE, STRINGS["en"])


def current_language() -> str:
    return next(code for code, table in STRINGS.items() if table is _ACTIVE)


def set_language(code: str) -> None:
    """Switch the UI language for this process; callers rebuild their controls."""
    global _ACTIVE
    _ACTIVE = STRINGS.get(code, _ACTIVE)


def get_string(key: str, **kwargs: object) -> str:
    text = _ACTIVE.get(key) or STRINGS["en"].get(key, key)
    if kwargs:
        try:
            return text.format(**kwargs)
        except KeyError:
            return text
    return text
